### ISSUE TITLE
Npm package

### ISSUE THREAD

**Issue by Kylart** [synecx/zettai#1]
Hello,

Nice work on this!

Would you mind setting up a `npm` package from this? It would be really useful as it's the first anime parser fully written in JS I see and I do think it's on par with Erengy's [anitomy](https://github.com/erengy/anitomy)!

**Comment by synecx** [comment]
Yes, I will set it up soon.

**Comment by synecx** [comment]
I have uploaded the package.

https://www.npmjs.com/package/zettai
